name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          HOST: ${{ secrets.SSH_ADDRESS }}
          USER: ${{ secrets.SSH_USER }}
          REPO_URL: ${{ github.repositoryUrl }}
          BRANCH: ${{ github.ref_name }}
        run: |
          echo "$PRIVATE_KEY" > github-ec2.pem
          chmod 600 github-ec2.pem

          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} 'bash -s' <<'EOF'
            set -e

            REPO_DIR="$HOME/steamscout"

            if [ -d "$REPO_DIR/.git" ]; then
              cd "$REPO_DIR"
              git pull origin "$BRANCH"
            else
              git clone "$REPO_URL" "$REPO_DIR"
              cd "$REPO_DIR"
            fi

            docker build -t steamscout .

            # Stop and remove any existing container
            docker stop steamscout || true
            docker rm steamscout || true

            # Run the new container
            docker run -d --name steamscout -p 80:80 steamscout
          EOF



